### ISSUE TITLE
Create the programs section of unit1

### ISSUE THREAD

**Issue by bananas24** [dammers2/psp#35]
In the `unit1` folder, add a file named `programs.md` and add documentation about Programs

**Comment by delgueero** [comment]
@bananas24 we don't understand what we have to do exactly. We have to search for information about what kind of programs? Thank you.

**Comment by bananas24** [comment]
@delgueero you need to take synthesize the most importan aspects of Computer programs, and how they relate to this course.
Take as an example: https://en.wikipedia.org/wiki/Computer_program
